version: "3"

services:
    web:
        build: .
        environment:
            - GOOGLE_APPLICATION_CREDENTIALS="key.json"
        ports:
            - "5000:5000"
        depends_on:
            - redis
    redis:
        image: redis
